### ISSUE TITLE
captcha issue

### ISSUE THREAD

**Issue by ssvaccine** [AmmeySaini/Chegg-Answer-Bot#17]
Thank you for this project!

It is very helpful but from yesterday, it returns captcha issue like below.
And Can i have a solution for it?

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Access to this page has been denied.</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet">
    <style>
        html, body {
            margin: 0;
            padding: 0;
            font-family: 'Open Sans', sans-serif;
            color: #000;
        }

        a {
            color: #c5c5c5;
            text-decoration: none;
        }

        .container {
            align-items: center;
            display: flex;
            flex: 1;
            justify-content: space-between;
            flex-direction: column;
            height: 100%;
        }

        .container > div {
            width: 100%;
            display: flex;
            justify-content: center;
        }

        .container > div > div {
            display: flex;
            width: 80%;
        }

        .customer-logo-wrapper {
            padding-top: 2rem;
            flex-grow: 0;
            background-color: #fff;
            visibility: hidden;
        }

        .customer-logo {
            border-bottom: 1px solid #000;
        }

        .customer-logo > img {
            padding-bottom: 1rem;
            max-height: 50px;
            max-width: 100%;
        }

        .page-title-wrapper {
            flex-grow: 2;
        }

        .page-title {
            flex-direction: column-reverse;
        }

        .content-wrapper {
            flex-grow: 5;
        }

        .content {
            flex-direction: column;
        }

        .page-footer-wrapper {
            align-items: center;
            flex-grow: 0.2;
            background-color: #000;
            color: #c5c5c5;
            font-size: 70%;
        }

        @media (min-width: 768px) {
            html, body {
                height: 100%;
            }
        }
    </style>
    
    
</head>

<body>
<section class="container">
    <div class="customer-logo-wrapper">
        <div class="customer-logo">
            <img src="" alt="Logo"/>
        </div>
    </div>
    <div class="page-title-wrapper">
        <div class="page-title">
            <h1>Please verify you are a human</h1>
        </div>
    </div>
    <div class="content-wrapper">
        <div class="content">

            <div id="px-captcha">
            </div>
            <p>
                Access to this page has been denied because we believe you are using automation tools to browse the
                website.
            </p>
            <p>
                This may happen as a result of the following:
            </p>
            <ul>
                <li>
                    Javascript is disabled or blocked by an extension (ad blockers for example)
                </li>
                <li>
                    Your browser does not support cookies
                </li>
            </ul>
            <p>
                Please make sure that Javascript and cookies are enabled on your browser and that you are not blocking
                them from loading.
            </p>
            <p>
                Reference ID: #e9f57454-2ce7-11ec-829c-45416b765673
            </p>
        </div>
    </div>
    <div class="page-footer-wrapper">
        <div class="page-footer">
            <p>
                Powered by
                <a href="https://www.perimeterx.com/whywasiblocked">PerimeterX</a>
                , Inc.
            </p>
        </div>
    </div>
</section>

<script>
    window._pxAppId = 'PXzYvFOXaC';
    window._pxJsClientSrc = '/zYvFOXaC/init.js';
    window._pxFirstPartyEnabled = true;
    window._pxVid = '';
    window._pxUuid = 'e9f57454-2ce7-11ec-829c-45416b765673';
    window._pxHostUrl = '/zYvFOXaC/xhr';
</script>
<script>
    var s = document.createElement('script');
    s.src = '/zYvFOXaC/captcha/captcha.js?a=c&u=e9f57454-2ce7-11ec-829c-45416b765673&v=&m=0';
    var p = document.getElementsByTagName('head')[0];
    p.insertBefore(s, null);
    if (true) {
        s.onerror = function () {`

**Comment by AliBakrOfficial** [comment]
I have same issues plz help

**Comment by 0xjas0** [comment]
Read labels

**Comment by AliBakrOfficial** [comment]
but why ?!

**Comment by AliBakrOfficial** [comment]
its working in my Local Pc but doesn't work any more in my VPS server & redirect to captcha verification
i know that we can't bypass captcha but i want to know how can Chegg Detect my server ?

**Comment by 0xjas0** [comment]
Probably cause you are spamming their server with many requests.
Or maybe you are logging your single account from different locations, doing so your acc gets flagged.
