### ISSUE TITLE
I have more less the same code for chegg discord bot. its giving me this error. what could be the problem.

### ISSUE THREAD

**Issue by Half-Note** [AmmeySaini/Chegg-Answer-Bot#2]
Traceback (most recent call last):
  File "E:\cc\c\bot.py", line 14, in <module>
    acc = CheggAccount(setup['CheggEmail'], setup['CheggPassword'])
  File "E:\cc\c\chegg.py", line 11, in __init__
    if (self.login(username, password) == False):
  File "E:\cc\c\chegg.py", line 78, in login
    if j['mfaChallengeDetails'] != None:
KeyError: 'mfaChallengeDetails'

**Comment by 0xjas0** [comment]
It's json key error
Probably not coded in a right way to check for MFA

**Comment by Half-Note** [comment]
can you check it if I send you the code..

**Comment by Half-Note** [comment]
import requests
import json
import base64
from datetime import datetime, timedelta


class CheggAccount:
    def __init__(self, username, password):
        self.token = None
        self.expiry = None
        if (self.login(username, password) == False):
            del self

    def valid_token(func):
        def wrapper_do_twice(self, *args, **kwargs):
            if datetime.now() > self.expiry:
                self.refresh()
            return func(self, *args, **kwargs)
        return wrapper_do_twice

    def mfa(self, j):
        headers = {
            'authorization': 'Basic MFQxOE5HYmFsUURGYzBnWkh6b3ZwZVJkN0E1Y3BMQ3g6dnRnamFZa3Ric2p4OUFPUg==',
            'accept': 'application/json',
            'user-agent': 'CheggApp/3.40.0 (com.chegg.mobile.consumer; build:3.40.0.0; iOS 14.5.0) Alamofire/5.2.2',
        }
        mfaToken = j['mfaChallengeDetails']['mfaToken']
        mfaFactor_id = j['mfaChallengeDetails']['factors'][0]['id']
        data = {
            'factor_id': mfaFactor_id,
            'mfa_token': mfaToken
        }

        response = requests.post(
            'https://proxy.chegg.com/oidc/mfa', headers=headers, data=data)

        j = json.loads(response.content)
        mfaEventId = j["mfaEventId"]
        code = False
        data = {'grant_type': 'mfa_code', 'mfa_code': code, 'mfa_event_id': mfaEventId,
                'mfa_token': mfaToken, 'source_page': 'ios CheggApp 3.39.1|cs', 'source_product': 'ios|cs'}
        while True:
            try:
                code = int(input(
                    "Triggered 2 factor authentication. Please enter the code to sent to your email: "))
            except ValueError:
                print("You didn't enter a number")
                continue
            data['mfa_code'] = code
            response = requests.post(
                'https://proxy.chegg.com/oidc/token', headers=headers, data=data)
            j = json.loads(response.content)
            if ('error' in j):
                print("invalid code. Please enter code again: ")
            else:
                return j

    def login(self, username, password):
        headers = {
            'authorization': 'Basic MFQxOE5HYmFsUURGYzBnWkh6b3ZwZVJkN0E1Y3BMQ3g6dnRnamFZa3Ric2p4OUFPUg==',
            'accept': 'application/json',
            'user-agent': 'CheggApp/3.40.0 (com.chegg.mobile.consumer; build:3.40.0.0; iOS 14.5.0) Alamofire/5.2.2',
        }
        data = {
            'grant_type': 'password',
            'source_page': 'ios CheggApp 3.36.0|cs',
            'source_product': 'ios|cs',
            'username': username,
            'password': password
        }
        response = requests.post(
            'https://proxy.chegg.com/oidc/token', headers=headers, data=data)
        j = json.loads(response.content)
        if ('error' in j):
            print(j['error'])
            return False

        if j['mfaChallengeDetails'] != None:
            j = self.mfa(j)
        self.token = j['access_token']
        self.refresh_token = j['refresh_token']
        self.expiry = datetime.utcfromtimestamp(
            j['issued_at']/1000.0) + timedelta(seconds=j['expires_in'])
        print("Login", self.expiry)
        return True

    def refresh(self):
        headers = {
            'authorization': 'Basic MFQxOE5HYmFsUURGYzBnWkh6b3ZwZVJkN0E1Y3BMQ3g6dnRnamFZa3Ric2p4OUFPUg==',
            'user-agent': 'CheggApp/3.40.0 (com.chegg.mobile.consumer; build:3.40.0.0; iOS 14.5.0) Alamofire/5.2.2',
        }
        url = 'https://proxy.chegg.com/oidc/token'
        data = {
            "grant_type": "refresh_token",
            'refresh_token': self.refresh_token,
        }
        response = requests.post(url, data=data, headers=headers)
        j = json.loads(response.content)
        self.token = j['access_token']
        self.refresh_token = j['refresh_token']
        self.expiry = datetime.utcfromtimestamp(
            j['issued_at']/1000.0) + timedelta(seconds=j['expires_in'])
        print("Refreshed", self.expiry)

    @valid_token
    def get_question_info(self, cheggurl):
        ret = {}
        sourceheaders = {
            'authority': 'www.chegg.com',
            'sec-ch-ua': '"Google Chrome";v="88", "Chromium";v="88", ";Not A Brand";v="99"',
            'sec-ch-ua-mobile': '?0',
            'upgrade-insecure-requests': '1',
            'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_4) AppleWebKit/538.36 (KHTML, like Gecko) Chrome/88.0.4389.82 Safari/537.36',
            'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
            'sec-fetch-site': 'none',
            'sec-fetch-mode': 'navigate',
            'sec-fetch-user': '?1',
            'sec-fetch-dest': 'document',
            'accept-language': 'en-US,en;q=0.9',
        }
        page = requests.get(cheggurl, headers=sourceheaders)
        with open("random.html", "w" ,encoding="utf-8") as f:
            f.write(page.text)

        uuid = page.text.split('pageNameDetailed":"')
        if (len(uuid) == 1):
            uuid = page.text.split('uuid":"')
        uuid = uuid[1].split('"')[0]
        headers = {
            'accept': 'application/vnd.chegg-odin.v1+json',
            'authorization': 'Basic MFQxOE5HYmFsUURGYzBnWkh6b3ZwZVJkN0E1Y3BMQ3g6dnRnamFZa3Ric2p4OUFPUg==',
            'access_token': self.token,
        }
        # Textbook
        if ("/questions-and-answers/" not in cheggurl):
            isbn = uuid.split("-")[0]
            problemid = uuid.split("-")[1]
            response = requests.get(
                f"https://proxy.chegg.com/content/tbs-problem/{problemid}.html")
            ret['htmlquestion'] = response.text
            data = f'{{"userAgent":"Mobile","problemId":"{problemid}","isbn13":"{isbn}"}}'
            response = requests.post(
                'https://proxy.chegg.com/v1/tbs/_/solution', headers=headers, data=data)
            j = response.json()
            steps = j['result']['solutions'][0]['steps']
            ret['htmlanswer'] = ''
            for s in steps:
                resp = requests.get(s['link'])
                ret['htmlanswer'] += resp.text
            aid = j['result']['solutions'][0]['id']
            entitytype = 'SOLUTION'
        else:
            entitytype = 'ANSWER'
            response = requests.get(
                f'https://proxy.chegg.com/v1/question/{uuid}', headers=headers)
            j = response.json()
            ret['htmlquestion'] = j['result']['content']['content']
            anstemplate = j['result']['availableAnswerTemplates']
            if 'ENHANCED_CONTENT_V2' in anstemplate:
                params = (
                    ('f.questionUUIDs', uuid),
                    ('f.templateNames', 'ENHANCED_CONTENT_V2'),
                )
                response = requests.get(
                    'https://proxy.chegg.com/v1/structuredAnswer', headers=headers, params=params)
                j = response.json()
                aid = j['result'][0]['id']
                b64answer = j['result'][0]['content']['body']
                j = json.loads(base64.b64decode(b64answer).decode('utf-8'))
                ret['htmlanswer'] = ''
                for s in j['steps']:
                    ret['htmlanswer'] += s['text'] + s['explanation']
            else:
                params = (
                    ('f.questionUUIDs', uuid),
                    ('limit', '100'),
                )
                url = "https://proxy.chegg.com/v1/answer"
                response = requests.get(url, headers=headers, params=params)
                j = response.json()
                steps = j['result']
                if steps == []:
                    ret['htmlanswer'] = None
                    return ret
                elif (steps[0]['accessDetails']['accessRestrictions'] != ['ACCOUNT_OK']):
                    return 'ACC_FLAGGED'
                ret['htmlanswer'] = ''
                for s in steps:
                    ret['htmlanswer'] += s['content']['content']
                aid = j['result'][0]['legacyId']
        headers.pop('accept')
        params = (
            ('f.entityType', entitytype),
            ('q', 'count=reviewType,reviewValue'),
            ('f.entityId', aid),
            ('f.ignoreUserId', 'true'),)
        response = requests.get(
            'https://proxy.chegg.com/v1/review', headers=headers, params=params)
        j = response.json()
        for r in j['result']:
            if r['reviewValue'] == '0':
                ret['likes'] = r['count']
            else:
                ret['dislikes'] = r['count']
        return ret

**Comment by TresorChun** [comment]
If you are willing to do this for me and add bot to my server, I am ready to pay for this service dear saini.

**Comment by 0xjas0** [comment]
@Half-Note better ask the author of the code to fix it
