### ISSUE TITLE
Captcha verification is causing issues

### ISSUE THREAD

**Issue by node-mysql-event** [AmmeySaini/Chegg-Answer-Bot#4]
While fetching the answers, sometimes Chegg redirects to Recaptcha verification. This will leads to script failure. Please help with this issue.

**Comment by 0xjas0** [comment]
You need to limit your requests, we won't be working to bypass the captcha

**Comment by valkin123** [comment]
> You need to limit your requests, we won't be working to bypass the captcha

How many requests in a time period do you believe would cause the captcha?
