### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Rohitjoshi07** [AmmeySaini/Chegg-Answer-Bot#5]
Showing Recaptcha page every time when trying to get an answer.

**Comment by Rohitjoshi07** [comment]
Fine now!Need to control the number of requests. Some random delay in the code will be good.

**Comment by riyazkhan1432021** [comment]
Hi Rohitjoshi how to control number of requests can u tell me

**Comment by riyazkhan1432021** [comment]
@Rohitjoshi07 hi i want small help can You message me in discord riyazkhan1432021#7051
