### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by xlLuKe** [AmmeySaini/Chegg-Answer-Bot#6]
it says ( list index out of range ) for the caption, and stat is FALSE

**Comment by 0xjas0** [comment]
Use it within limits as chegg can flag the acc if you are sending too many requests

**Comment by devilevil100** [comment]
Opening the issue cause having the same issue right now. Just done with setup and tried but this error comes.

**Comment by xlLuKe** [comment]
Yeh I got the same comment until now, I didn't even send too many requests. I don't really know whats the problem.

**Comment by devilevil100** [comment]
Yeah please check dude and thank you for making this

**Comment by devilevil100** [comment]
hey i think i fixed the code in helper.py line 150 change js = json.loads(dd.text) to js = json.loads(dd.string) and it was fixed

**Comment by devilevil100** [comment]
> Yeh I got the same comment until now, I didn't even send too many requests. I don't really know whats the problem.

hey i got it fixed u have discord hmu Wusername#7080

**Comment by 0xjas0** [comment]
Send me the questions link where you all are getting errors with proper error screenshots

**Comment by riyazkhan1432021** [comment]
Hi Saini is the chegg bot will be working for life time or not

**Comment by devilevil100** [comment]
> Send me the questions link where you all are getting errors with proper error screenshots

hey just change dd.text to dd.string everything works fine then

**Comment by riyazkhan1432021** [comment]
@devilevil100  in which we have to change  can u plz help 
 this one change dd.text to dd.string everything works fine then

**Comment by devilevil100** [comment]
> @devilevil100 in which we have to change can u plz help
> this one change dd.text to dd.string everything works fine then

helper.py line 150 i think

**Comment by riyazkhan1432021** [comment]
@devilevil100  Pycharm is okay for compling or any other needed

**Comment by riyazkhan1432021** [comment]
@devilevil100 plz help with this 
![image](https://user-images.githubusercontent.com/86786070/125176927-43765e00-e1f5-11eb-8230-73a0075bb89a.png)

**Comment by riyazkhan1432021** [comment]
@devilevil100  can u plz message me in discord i have a dout plz id you don't mind riyazkhan1432021#7051

**Comment by Muhammad-Ahsan-Rasheed** [comment]
> @devilevil100 in which we have to change can u plz help
> this one change dd.text to dd.string everything works fine then

I'd try the same but it still popup as "list index out of range" and its just throwing the error with no output from "getQuesAns"
![Uploading image.png…]()

**Comment by riyazkhan1432021** [comment]
@Muhammad-Ahsan-Rasheed  show your pic where is coming error

**Comment by Muhammad-Ahsan-Rasheed** [comment]
![Capture](https://user-images.githubusercontent.com/69692532/126115771-3c12c5a5-2936-447d-b865-2ac57902099b.PNG)

**Comment by Muhammad-Ahsan-Rasheed** [comment]
![image](https://user-images.githubusercontent.com/69692532/126115945-0354485a-a62b-4188-a750-e535e0387297.png)

**Comment by riyazkhan1432021** [comment]
@Muhammad-Ahsan-Rasheed  u are using first time or..

**Comment by Muhammad-Ahsan-Rasheed** [comment]
@riyazkhan1432021 Yes I've done same steps for helper and just updated the bot script but it throw error and not going beyond line 24 in main.py

**Comment by riyazkhan1432021** [comment]
@Muhammad-Ahsan-Rasheed have you given token there

**Comment by Muhammad-Ahsan-Rasheed** [comment]
@riyazkhan1432021 Yes Token is stored in system variable and bot is showing its status active and also responding to messages but Only giving error in **"def getQAns(self, ques_url):"** function and state the error as **"list index out of range"**...

**Comment by riyazkhan1432021** [comment]
@Muhammad-Ahsan-Rasheed  have you changed the helper. Py in the line 150 dd.text to dd.string and don't change anything thing in setup and helper.py or in your bot program only same mistakes will be there

**Comment by Muhammad-Ahsan-Rasheed** [comment]
@riyazkhan1432021 Yes I did only changed the **dd.text** to **dd.string** and didn't touch anything instead of Bot.py. In **bot.py** it is executing **till line 24 and after that it throws the error**.

**Comment by riyazkhan1432021** [comment]
@Muhammad-Ahsan-Rasheed  your bot code will be wrong and it would be ban your account also

**Comment by Muhammad-Ahsan-Rasheed** [comment]
@riyazkhan1432021 Please check out my bot.py code... My chegg account is working Perfectly fine.

import discord
import os
from helper import CheggHelper

token = os.environ['Token']

bot = discord.Client()
obj = CheggHelper()

@bot.event
async def on_ready():
  print(f'Bot is active as {bot.user}')

@bot.event
async def on_message(message):
  if message.author == bot.user:
    return
  
  if message.content.startswith('?chegg '):
    await message.channel.send('Chegg link received!!')
    try:
        ques_link = message.content.split(' ')[1]
        #print(ques_link)
        stat, filex, captionx = obj.getQAns(ques_link)
        if stat == True:
            bot.send(message.channel, open(filex, 'rb'))
            os.remove(filex)
        else:
            await message.channel.send(message, captionx)
    except Exception as e:
        await message.channel.send(str(e))
  else:
    await message.channel.send('Not a chegg link!!')

bot.run(token)

**Comment by riyazkhan1432021** [comment]
@Muhammad-Ahsan-Rasheed  I can't check I don't have time to check the code it's take so much time and if u again and again excited ur acc will ban

**Comment by Muhammad-Ahsan-Rasheed** [comment]
@riyazkhan1432021 Okay Thanks... 😊 no problem..

**Comment by riyazkhan1432021** [comment]
@Muhammad-Ahsan-Rasheed  u can use for telegram bot instead of discord give delay as 60 sec per request

**Comment by Muhammad-Ahsan-Rasheed** [comment]
@riyazkhan1432021 Where I can find the **Channel ID** during **Two Factor Authentication**? I've paid chegg account...

**Comment by riyazkhan1432021** [comment]
@Muhammad-Ahsan-Rasheed  inbox me in discord riyazkhan1432021#7051

**Comment by Ednn0nd1au** [comment]
@riyazkhan1432021 Hi, I think the issue still happened even change dd.text as dd.string. Would you please give me a contact so we can discuss further please~
