### ISSUE TITLE
After two hours or less, it gives a message that the Access Token has expired

### ISSUE THREAD

**Issue by Ali-Adnan219** [AmmeySaini/Chegg-Answer-Bot#8]

**Comment by riyazkhan1432021** [comment]
@AliAdnanc7  hi can u message me in telegram @hareeb143

**Comment by Rohitjoshi07** [comment]
@AliAdnanc7  in this case you need to run the setup.py again. Your access token has a time validity of approx 30 minutes if you do not use the bot for long time then the access token and refresh token will expire so you need to generate again by logging in using setup.py. Thanks

**Comment by AliAdnanc7** [comment]
Thanks for the reply
In this case the bot will not work perfectly.....because every 30 minutes the bot needs to run setup.py.......is there another way to make the bot run for days without setup.py

**Comment by Ali-Adnan219** [comment]
> @AliAdnanc7 in this case you need to run the setup.py again. Your access token has a time validity of approx 30 minutes if you do not use the bot for long time then the access token and refresh token will expire so you need to generate again by logging in using setup.py. Thanks

Thanks for the reply
In this case the bot will not work perfectly.....because every 30 minutes the bot needs to run setup.py.......is there another way to make the bot run for days without setup.py

**Comment by devilevil100** [comment]
hey @AliAdnanc7  i can do it for you. hit me up on discord Wusername#7080

**Comment by Ali-Adnan219** [comment]
> hey @AliAdnanc7 i can do it for you. hit me up on discord Wusername#7080
I sent you a message

**Comment by stardustnova06** [comment]
Hey @AliAdnanc7 if you still need help you can message me on Discord "masterofall#0129"

**Comment by AliAdnanc7** [comment]
> Hey @AliAdnanc7 if you still need help you can message me on Discord "masterofall#129"

![Uploading Screenshot_20210719_030647_com.discord.jpg…]()

**Comment by Ali-Adnan219** [comment]
> Hey @AliAdnanc7 if you still need help you can message me on Discord "masterofall#129"

An error appears for a search for your name... for a search that appears to me, it takes 4 tag to search for a person... Check your name or owner ID

**Comment by stardustnova06** [comment]
It is masterofall#0 1 2 9

**Comment by Ali-Adnan219** [comment]
> It is masterofall#0 1 2 9
AliS219#1673

**Comment by Muhammad-Ahsan-Rasheed** [comment]
Where I can find the **Channel ID** during the 2 factor Authentication?

**Comment by devilevil100** [comment]
> Where I can find the **Channel ID** during the 2 factor Authentication?

hey there u can contact me on discord "Wusername#7080"
