### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by riyazkhan1432021** [AmmeySaini/Chegg-Answer-Bot#9]
![image](https://user-images.githubusercontent.com/86786070/125176868-c34ff880-e1f4-11eb-83e8-5ca623933b88.png)
@AmmeySaini what is the error can u tell

**Comment by Rohitjoshi07** [comment]
when it asks for channel id. Enter 1

**Comment by riyazkhan1432021** [comment]
yes for channel id @Rohitjoshi07

**Comment by riyazkhan1432021** [comment]
again t is showing error plz tell me can you message in discord riyazkhan1432021#7051
